// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var host, xzbApp, xzbAppControllers, xzbAppDirectives, xzbAppFilters, xzbAppServices;

  xzbApp = angular.module('xzbApp', ['xzbApp.controllers', 'xzbApp.directives', 'xzbApp.filters', 'xzbApp.services']);

  xzbApp.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/', {
        templateUrl: 'partials/article-list.html',
        controller: 'ArticleListCntl'
      });
      $routeProvider.when('/detail/:id', {
        templateUrl: 'partials/article-detail.html',
        controller: 'ArticleDetailCntl'
      });
      return $routeProvider.otherwise({
        redirectTo: '/'
      });
    }
  ]);

  xzbAppControllers = angular.module('xzbApp.controllers', ['xzbApp.services']);

  xzbAppControllers.controller('ArticleListCntl', [
    '$scope', 'articleService', function(scope, _articleService) {
      return scope.articles = _articleService.query();
    }
  ]);

  xzbAppControllers.controller('ArticleDetailCntl', [
    '$scope', '$routeParams', 'articleService', function(scope, routeParams, _articleService) {
      return scope.article = _articleService.get({
        id: routeParams.id
      }, function(article) {});
    }
  ]);

  xzbAppDirectives = angular.module('xzbApp.directives', []);

  xzbAppDirectives.directive('appVersion', [
    'version', function(version) {
      return function(scope, elm, attrs) {
        return elm.text(version);
      };
    }
  ]);

  xzbAppFilters = angular.module('xzbApp.filters', []);

  xzbAppFilters.filter('interpolate', [
    'version', function(version) {
      return function(text) {
        return String(text).replace(/\%VERSION\%/mg, version);
      };
    }
  ]);

  host = "http://173.255.227.47\\:8081";

  xzbAppServices = angular.module('xzbApp.services', ['ngResource']);

  xzbAppServices.value('version', '0.0.1');

  xzbAppServices.factory('articleService', function($resource) {
    return $resource("" + host + "/:verb", {}, {
      get: {
        method: 'GET',
        params: {
          verb: 'api_get_post',
          id: ''
        }
      },
      query: {
        method: 'GET',
        params: {
          verb: 'api_list_user_post',
          userid: 'denny',
          date: '2013-01-24'
        },
        isArray: true
      }
    });
  });

  /*
  xzbAppServices.factory 'articleService', ($resource) ->
  	$resource 'articles/:id.json', {},
  		query:
  			method: 'GET'
  			params:
  				id: 'articles'
  			isArray: true
  */


}).call(this);
